version: '2' 
services:
     web:
      build: ./app
      container_name: server
      ports:
        - "8080:8080"
      restart: always
      links:
        - db
     db:
       build: ./db
       container_name: mysql
       restart: always
       environment:
         MYSQL_DATABASE: library
         MYSQL_ROOT_PASSWORD: test
         MYSQL_ROOT_HOST: 0.0.0.0
         MYSQL_USER: root
         MYSQL_PASSWORD: test
      #  volumes:
        #  - "./init/:/docker-entrypoint-initdb.d/"
       ports:
         - "3306:3306"