insert into book(title) values('Typescript quick start');
insert into book(title) values('The selfish gene');
insert into book(title) values('Springboot quick start');
insert into book(title) values('Operating system');
insert into book(title) values('God of java');
insert into book(title) values('Spring quick start');
insert into book(title) values('Algorithm training');
insert into book(title) values('Effective java');
insert into book(title) values('DL learning from Scratch');
insert into book(title) values('Object');
insert into book(title) values('Inside Javascript');